# roles/customizations/tasks/install_sublime.yml
---
# ! apt-key is deprecated in newer debian installs. Work around -> Import the GPG key directly into /etc/apt/keyrings and reference it in the repository configuration.
# - name: Add Sublime Text Key
#   ansible.builtin.apt_key:
#     url: https://download.sublimetext.com/sublimehq-pub.gpg
#     state: present
#
# - name: Add Sublime Text repository
#   ansible.builtin.apt_repository:
#     repo: deb https://download.sublimetext.com/ apt/stable/
#     state: present

- name: Add Sublime Text GPG key
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/keyrings/sublimehq-pub.gpg
    mode: "0644"

- name: Add Sublime Text repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/sublimehq-pub.gpg] https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime-text

- name: Install Sublime Text
  ansible.builtin.apt:
    name:
      - sublime-text
    state: present
    update_cache: true

# Config dirs not created before first run
- name: Create sublime user package directory
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "{{ sublime_config_dir }}"
    state: directory
    recurse: true
    mode: "0700"

- name: Copy Sublime preferences
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.copy:
    remote_src: false
    src: "files/sublime/{{ item }}"
    dest: "{{ sublime_config_dir }}"
    mode: "0644"
  loop:
    - Markdown.sublime-settings
    - "Package Control.sublime-settings"
    - Preferences.sublime-settings
    - python-black.sublime-settings
    - Python.sublime-settings
