---
extends: relaxed

rules:
  line-length: disable
  # line-length:
  #   max: 260

  truthy:
    allowed-values: ["true", "false"]
    check-keys: true

  # document-start:
  #   present: false

  # comments:
  #   min-spaces-from-content: 1
  comments-indentation: disable
