---
extends: relaxed

rules:
  line-length: disable
  # line-length:
  #   max: 260

  truthy:
    allowed-values: ["true", "false"]
    check-keys: true

  comments:
    min-spaces-from-content: 1

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
