---
- name: Configure Kali
  hosts: all
  gather_facts: true
  vars:
    new_vm: true
    setup_dotfiles: false
    clone_notes: false
    customize: true

  tasks:
    - name: Execute roles
      block:
        - name: First run
          ansible.builtin.include_role:
            name: first_run
          when: new_vm

        - name: Setup dotfiles
          ansible.builtin.include_role:
            name: dotfiles
          when: setup_dotfiles

        - name: Install tools
          ansible.builtin.include_role:
            name: install_tools

        - name: Clone personal notes
          ansible.builtin.include_role:
            name: notes
          when: clone_notes

        - name: Customizations
          ansible.builtin.include_role:
            name: customizations
          when: customize
