# roles/notes/tasks/clone_private_repos.yml
---
- name: Check if private keys exists
  ansible.builtin.find:
    paths: "/home/{{ ansible_user }}/.ssh"
    patterns:
      - "thm_github*"
      - "htb_github*"
      - "ctfs_github*"
      - "digitalGarden_github*"
  register: identiy_keys

- name: Clone private repos
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item.split('/')[-1].replace('.git', '') }}"
    update: true
    single_branch: false
    accept_newhostkey: true
    depth: 1
  loop: "{{ private_repos }}"
  when: identiy_keys.files | length > 0
# noqa: latest
