# roles/dotfiles/tasks/install_tools.yml
---
- name: Clone fzf repository
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "/home/{{ ansible_user }}/.fzf"
    depth: 1

- name: Install fzf w/o any shell modifications
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell:
    cmd: "/home/{{ ansible_user }}/.fzf/install --no-update-rc --no-bash --no-zsh"
  # noqa: command-instead-of-shell
  # noqa: no-changed-when

- name: Install packages with apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  when: ansible_facts['ansible_os_family'] == 'Debian'

- name: Install packages with pacman
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_packages }}"
  when: ansible_facts['ansible_os_family'] == 'Arch'
