# roles/dotfiles/tasks/install_starship.yml
---
- name: Install Starship prompt
  ansible.builtin.shell:
    cmd: curl -sS https://starship.rs/install.sh | sh
  args:
    creates: "/usr/local/bin/starship"
  # noqa: risky-shell-pipe
  # noqa: command-instead-of-module
