# roles/first_run/tasks/pre_tasks.yml
---
- name: Update repos
  tags: update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install apt-transport-https package
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Configure apt for HTTPS and set berkeley repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "^deb http://"
    line: "deb https://mirrors.ocf.berkeley.edu/kali/ kali-rolling main contrib non-free"
