---
# vars file for dotfiles
dotfiles_repo: "git@dotfiles.github.com:AbraXa5/dotfiles"
dotfiles_dest: "{{ ansible_facts['user_dir'] }}/.dotfiles.git"
dotfiles_version: main

starship: true

# packages for dotfiles
apt_packages:
  - bat
  # - exa # Removed from repos, replaced by eza
  - silversearcher-ag
  - xclip
  - nnn
  - peco
  - jq
  - python3
  # - python3-pip  # managed by uv
  - python3-venv
  - unzip
  - nmap
  - remmina
  - fortune-mod
  - toilet
  - cowsay
  - golang-go
pacman_packages:
  - bat
  - exa
  - the_silver_searcher
  - xclip
  - nnn
  - peco
  - jq
  - python3
  # - python3-pip  # managed by uv
  - python3-venv
  - unzip
  - nmap
  - remmina
  - fortune-mod
  - toilet
  - cowsay
  - go
