# roles/install_tools/tasks/install_caido.yml
---
- name: Create caido directory
  ansible.builtin.file:
    path: "{{ tools_dir }}/Caido"
    state: directory
    mode: "0755"

- name: Download cargo from releases
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ tools_dir }}/Caido/{{ item | basename }}"
    mode: "0755"
  loop:
    - "https://caido.download/releases/v{{ caido_version }}/caido-desktop-v{{ caido_version }}-{{ base_os }}-x86_64.AppImage"
    - "https://caido.download/releases/v{{ caido_version }}/caido-cli-v{{ caido_version }}-{{ base_os }}-x86_64.tar.gz"

- name: Extract cargo CLI
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ tools_dir }}/Caido/caido-cli-v{{ caido_version }}-{{ base_os }}-x86_64.tar.gz"
    dest: "{{ tools_dir }}/Caido/"
