# roles/install_tools/tasks/install_pipx.yml
---
- name: Install pipx
  environment:
    PIP_REQUIRE_VIRTUALENV: "false"
  ansible.builtin.pip:
    name: pipx
    state: present

- name: Set pipx path
  ansible.builtin.command: python3 -m pipx ensurepath
  args:
    creates: "/home/{{ ansible_user }}/.local/bin/pipx"

- name: Install pipx modules
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop: "{{ pip_packages }}"

- name: "Install pipx tools via github"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.src }}"
    state: latest
  loop: "{{ pipx_git_install_tools }}"
