# roles/install_tools/tasks/install_cargo.yml
---
- name: Check if cargo directory exists
  ansible.builtin.stat:
    path: "{{ cargo_dir }}"
  register: cargo_dir_stat

- name: Install Cargo for rust
  when: not cargo_dir_stat.stat.exists
  block:
    - name: Download rust install script
      ansible.builtin.get_url:
        url: "https://sh.rustup.rs"
        dest: "/tmp/rust_install.sh"
        mode: "0755"

    - name: Run rust / cargo install script
      ansible.builtin.command: "/tmp/rust_install.sh --no-modify-path --profile default -y"
      args:
        creates: "{{ cargo_dir }}"

- name: Set PATH for cargo
  ansible.builtin.set_fact:
    cargo_path: "/home/kali/.cargo/bin/cargo"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ cargo_path }}"

- name: Install cargo packages
  community.general.cargo:
    name: "{{ item }}"
  loop: "{{ cargo_tools }}"
