# roles/install_tools/tasks/install_fzf.yml
---
- name: Check if FZF directory exists
  ansible.builtin.stat:
    path: "{{ fzf_dir }}"
  register: fzf_dir_stat

- name: Clone FZF repo
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ fzf_dir }}"
    update: true
    depth: 1
    # noqa: latest

- name: Run fzf install script w/o updating rc files
  ansible.builtin.command: "{{ fzf_dir }}/install --key-bindings --completion --no-update-rc"
  args:
    creates: ".fzf.zsh"
