# roles/install_tools/tasks/install_cargo.yml
---
- name: Check if cargo directory exists
  ansible.builtin.stat:
    path: "{{ cargo_dir }}"
  register: cargo_dir_stat

- name: Install Cargo for rust
  when: not cargo_dir_stat.stat.exists
  block:
    - name: Download rust install script
      ansible.builtin.get_url:
        url: "https://sh.rustup.rs"
        dest: "/tmp/rust_install.sh"
        mode: "0755"

    - name: Run rust install script
      ansible.builtin.command: "/tmp/rust_install.sh --no-modify-path --profile default -y"
      args:
        creates: "{{ cargo_dir }}"
