#!/usr/bin/env bash
# tools_cheatsheet.sh — Quick reference for CTF/pentest tools installed by ansible
# Usage: ./tools_cheatsheet.sh
#        ./tools_cheatsheet.sh | less -R
#        ./tools_cheatsheet.sh | grep -i "keyword"

BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RESET='\033[0m'

header() { printf "\n${BOLD}${CYAN}━━━ %s ━━━${RESET}\n" "$1"; }
tool()   { printf "  ${GREEN}%-26s${RESET} %s\n" "$1" "$2"; }

# ─── RECON / OSINT ───────────────────────────────────────────────────────────
header "RECON / OSINT"
tool "subfinder"           "Passive subdomain enumeration via dozens of APIs"
tool "assetfinder"         "Find domains/subdomains associated with a company"
tool "alterx"              "Subdomain permutation & alteration engine"
tool "dnsx"                "DNS bulk resolution, brute-force, wildcard filter"
tool "httprobe"            "Probe domains for live HTTP/HTTPS hosts"
tool "httpx (Go)"          "Fast HTTP probing toolkit with rich output & filtering"
tool "gau"                 "Collect known URLs from Wayback, CommonCrawl, OTX, URLScan"
tool "waybackurls"         "Fetch all known URLs for a domain from Wayback Machine"
tool "hakrawler"           "Web crawler focused on endpoint and link discovery"
tool "katana"              "Next-gen crawling framework with JS rendering support"
tool "gospider"            "Fast web spider with BlindXSS and form discovery"
tool "gowitness"           "~/Tools/gowitness — web screenshot & reporting (replaces aquatone)"
tool "gowitness (usage)"   "gowitness scan file -f urls.txt --screenshot-path ./shots"
tool "meg"                 "Fetch many paths for many hosts efficiently"
tool "unfurl"              "Extract domain/path/params from a list of URLs"
tool "gron"                "Transform JSON into discrete grep-able assignments"
tool "pup"                 "HTML parsing from the command line using CSS selectors"
tool "trufflehog"          "Scan git repos and filesystems for secrets & credentials"
tool "github-dorks"        "~/Tools/github-dorks — dork searches for exposed data on GitHub"
tool "gitrecon"            "~/Tools/gitrecon — OSINT: scrape GitHub user/repo metadata"
tool "GitTools"            "~/Tools/GitTools — dump & extract exposed .git repositories"
tool "mailcat"             "~/Tools/mailcat — OSINT: find accounts linked to an email"
tool "L33tLinked"          "~/Tools/L33tLinked — LinkedIn username enum via email prefix"
tool "cloudflair"          "~/Tools/cloudflair — reveal origin IPs hidden behind Cloudflare"

# ─── WEB EXPLOITATION ────────────────────────────────────────────────────────
header "WEB EXPLOITATION"
tool "ffuf"                "Fast web fuzzer for content, vhost, parameter discovery"
tool "feroxbuster"         "Recursive content discovery and directory brute-forcing"
tool "wfuzz"               "Flexible web fuzzer with rich filter/match capabilities"
tool "nuclei"              "Template-based vuln scanner (HTTP/DNS/TCP/OOB/etc)"
tool "interactsh-client"   "OAST / out-of-band interaction server client (blind vulns)"
tool "interactsh-client (usage)" "interactsh-client — generates *.oast.fun callback URL"
tool "dalfox"              "XSS scanner and parameter analysis tool"
tool "XSStrike"            "~/Tools/XSStrike — advanced XSS detection with fuzzing"
tool "arjun"               "HTTP parameter discovery (GET/POST/JSON/XML)"
tool "caido"               "Modern web proxy for intercepting/replaying HTTP traffic"
tool "Burpsuite (jar)"     "~/Tools/Burpsuite/ — manual web app testing proxy suite"
tool "flask-unsign"        "Decode, forge, and brute-force Flask session cookies"
tool "jwt_tool"            "~/Tools/jwt_tool — JWT decode / forge / brute-force secrets"
tool "jwt-hack"            "JWT cracking and exploitation via YAML playbooks"
tool "cookie-monster"      "~/Tools/cookie-monster — exploit common cookie signing flaws"
tool "wafw00f"             "~/Tools/wafw00f — Web Application Firewall fingerprinting"
tool "SSRFmap"             "~/Tools/SSRFmap — SSRF exploiter across protocols/services"
tool "Gopherus"            "~/Tools/Gopherus — generate gopher payloads for SSRF smuggling"
tool "commix"              "~/Tools/commix — command injection detection & exploitation"
tool "CMSmap"              "~/Tools/CMSmap — CMS scanner (WordPress, Drupal, Joomla, Moodle)"
tool "droopescan"          "Drupal / SilverStripe plugin and version scanner"
tool "nginxpwner"          "~/Tools/nginxpwner — Nginx path traversal & misconfiguration scanner"
tool "php_filter_chain_gen" "~/Tools/php_filter_chain_generator — PHP filter RCE chain builder"
tool "s3scanner"           "Enumerate open/misconfigured S3 buckets and their contents"
tool "s3recon"             "Multi-provider cloud storage bucket reconnaissance"
tool "Photon"              "~/Tools/Photon — crawler extracting URLs, emails, files, API keys"
tool "NoSQLMap"            "~/Tools/NoSQLMap — NoSQL injection & MongoDB exploitation"

# ─── ACTIVE DIRECTORY / WINDOWS ──────────────────────────────────────────────
header "ACTIVE DIRECTORY / WINDOWS"
tool "netexec"             "Network services pentesting suite (CrackMapExec successor)"
tool "impacket"            "Python implementations of Windows network protocols (50+ tools)"
tool "bloodyAD"            "AD privilege escalation via LDAP/ADWS (no SMB required)"
tool "autobloody"          "Automated BloodHound attack path exploitation"
tool "certipy-ad"          "Active Directory Certificate Services (ADCS) attack toolkit"
tool "certsync"            "Dump NTLM hashes via LDAPS + ADCS without DA privileges"
tool "pyWhisker"           "~/Tools/pyWhisker — shadow credentials via msDS-KeyCredentialLink"
tool "PKINITtools"         "~/Tools/PKINITtools — PKINIT / UnPAC-the-hash / shadow creds"
tool "PassTheCert"         "~/Tools/PassTheCert — LDAPS auth from a stolen certificate"
tool "targetedKerberoast"  "~/Tools/targetedKerberoast — Kerberoast via ACL-based targeting"
tool "kerberoast"          "AS-REP roast & Kerberoast with hashcat/john-compatible output"
tool "kerbrute"            "Kerberos username enum, password spray, brute-force"
tool "windapsearch"        "LDAP enumeration via Go — users, groups, computers, SPNs"
tool "ldeep"               "In-depth LDAP enum — pulls AD objects, ACLs, trusts, etc."
tool "LDAPmonitor"         "~/Tools/LDAPmonitor — monitor LDAP changes in real-time"
tool "coercer"             "Trigger MS-RPRN/MS-EFSR/MS-FSRVP coercion for NTLM relay"
tool "krbrelayx"           "~/Tools/krbrelayx — Kerberos relay & unconstrained delegation abuse"
tool "aclpwn"              "Automated ACL-based privilege escalation path exploitation"
tool "pre2k"               "Exploit pre-Windows 2000 machine accounts (weak passwords)"
tool "DonPAPI"             "Remote DPAPI credential and secret dumping over the network"
tool "pypykatz"            "Mimikatz in Python — parse LSASS, DPAPI, SAM, NTDS secrets"
tool "bloodhound (py)"     "BloodHound CE ingestor: collect and upload AD attack-path data"
tool "RustHound"           "~/Tools/RustHound — fast BloodHound ingestor written in Rust"
tool "linWinPwn"           "~/Tools/linWinPwn — automated AD/network pentesting via impacket"
tool "ActiveDirAttackTool" "~/Tools/ActiveDirectoryAttackTool — automated AD attack chains"
tool "ADRecon"             "~/Tools/ADRecon — AD recon via LDAP / PowerShell"
tool "enum4linux-ng"       "~/Tools/enum4linux-ng — SMB/RPC/LDAP enumeration with JSON output"
tool "wesng"               "~/Tools/wesng — Windows Exploit Suggester: Next Generation"
tool "nishang"             "~/Tools/nishang — PowerShell offensive security framework"
tool "PowerSploit"         "~/Tools/PowerSploit — PowerShell post-exploitation framework"
tool "pywerview"           "~/Tools/pywerview — PowerView ported to Python for AD recon"
tool "PrivescCheck"        "~/Tools/PrivescCheck — PowerShell Windows privesc enumeration"
tool "Rubeus.exe"          "~/Tools/Rubeus.exe — C# Kerberos: TGT/TGS requests, roasting"
tool "Certify.exe"         "~/Tools/Certify.exe — C# ADCS misconfiguration finder (ESC1-8)"
tool "Seatbelt.exe"        "~/Tools/Seatbelt.exe — C# host situational awareness survey"
tool "SharpUp.exe"         "~/Tools/SharpUp.exe — C# privilege escalation checks"
tool "SafetyKatz.exe"      "~/Tools/SafetyKatz.exe — AV-safe Mimikatz via minidump"
tool "SharpKiller.exe"     "~/Tools/SharpKiller.exe — disable Windows Defender / AV products"
tool "SharpCollection"     "~/Tools/SharpCollection — precompiled .NET offensive tooling"
tool "GodPotato"           "~/Tools/GodPotato — potato privesc to NT AUTHORITY\\SYSTEM"
tool "PrintSpoofer"        "~/Tools/PrintSpoofer — SeImpersonate print spooler privesc"
tool "RoguePotato"         "~/Tools/RoguePotato — COM impersonation privesc"
tool "SweetPotato"         "~/Tools/SweetPotato — combines PrintSpoofer + EfsPotato"
tool "FullPowers.exe"      "~/Tools/FullPowers.exe — restore full token privs from services"
tool "manspider"           "Crawl SMB shares and search file contents for sensitive data"

# ─── NETWORK / TUNNELING / PIVOTING ──────────────────────────────────────────
header "NETWORK / TUNNELING / PIVOTING"
tool "ligolo-ng proxy"     "~/Tools/ligolo-ng/ — TUN-based pivot proxy (run on attacker)"
tool "ligolo-ng agent"     "~/Tools/ligolo-ng/ — TUN-based agent (run on pivot host)"
tool "ligolo-ng (win)"     "~/Tools/ligolo-ng/ — Windows agent for pivoting back"
tool "ligolo-ng (usage)"   "proxy: ./proxy -selfcert | agent: ./agent -connect ATTACKER:11601"
tool "chisel (linux)"      "~/Tools/chisel/ — fast TCP/UDP tunneling over HTTP with auth"
tool "chisel (windows)"    "~/Tools/chisel/ — Windows chisel agent"
tool "chisel (usage)"      "server: chisel server -p 8000 --reverse | client: chisel client IP R:port:0.0.0.0:port"
tool "naabu"               "Fast port scanner wrapping nmap for service/version detection"
tool "naabu (usage)"       "naabu -host 10.10.10.0/24 -p - | nmap -sV -iL -"
tool "rustscan"            "Scan all 65535 ports in seconds, pipe results to nmap"
tool "rustscan (usage)"    "rustscan -a 10.10.10.1 -- -sV -sC"
tool "dnschef"             "~/Tools/dnschef — DNS proxy/spoofer for selective DNS control"
tool "proxychains"         "Force TCP connections through SOCKS/HTTP proxy chains"

# ─── LINUX PRIVILEGE ESCALATION ──────────────────────────────────────────────
header "LINUX PRIVILEGE ESCALATION"
tool "linpeas.sh"          "~/Tools/linpeas.sh — Linux/Unix privesc script, comprehensive"
tool "pspy64 / pspy32"     "~/Tools/pspy/ — monitor processes & cron jobs without root"
tool "linux-smart-enum"    "~/Tools/linux-smart-enumeration — modular privesc enum script"
tool "LinEnum"             "~/Tools/LinEnum — local Linux enumeration & privesc checks"
tool "linux-exploit-suggester" "~/Tools/linux-exploit-suggester — map kernel version to CVEs"
tool "ltrace"              "Trace library calls made by a running process"

# ─── WINDOWS PRIVILEGE ESCALATION ────────────────────────────────────────────
header "WINDOWS PRIVILEGE ESCALATION"
tool "winPEAS.bat/.exe/.ps1" "~/Tools/winPEAS* — Windows privesc script (bat, exe, ps1)"
tool "Invoke-WinPEAS.txt"  "~/Tools/Invoke-WinPEAS — run winPEAS reflectively in-memory"
tool "PrivescCheck"        "~/Tools/PrivescCheck — PowerShell-based Windows privesc enum"
tool "SeatbeltNet4.exe"    "~/Tools/SeatbeltNet4AnyCPU.exe — .NET 4 survey for older targets"
tool "nmap.exe"            "~/Tools/nmap.exe — static nmap binary for Windows pivot hosts"

# ─── BINARY EXPLOITATION / REVERSING ─────────────────────────────────────────
header "BINARY EXPLOITATION / REVERSING"
tool "pwntools"            "CTF binary exploit development framework (cyclic, ROP, etc)"
tool "pwndbg"              "~/Tools/pwndbg — GDB plugin for exploit-dev quality-of-life"
tool "pwncat-cs"           "Bind/reverse shell handler with post-exploit module system"
tool "binsider"            "TUI binary inspector: segments, strings, symbols, syscalls"
tool "ghidra"              "NSA reverse engineering suite (disassembly, decompilation)"
tool "gdb"                 "GNU debugger — load with 'gdb ./binary'"
tool "dex2jar"             "Convert Android .dex (APK) to .jar for Java analysis"
tool "jd-gui"              "Java decompiler GUI — pair with dex2jar for APK reversing"
tool "apkurlgrep"          "Extract URLs/endpoints from APK files statically"
tool "jython.jar"          "~/Tools/Burpsuite/ — Python 2 on JVM for Burp/ysoserial scripts"
tool "ysoserial"           "~/Tools/ysoserial — Java deserialization payload generator"
tool "ysoserial.net"       "~/Tools/ysoserial.net — .NET deserialization payload generator"
tool "Decodify"            "~/Tools/Decodify — detect & decode recursively encoded strings"
tool "hardcodes"           "~/Tools/hardcodes — find hardcoded secrets in source code"

# ─── CRYPTO / PASSWORDS / HASHES ─────────────────────────────────────────────
header "CRYPTO / PASSWORDS / HASHES"
tool "search-that-hash"    "Identify hash type, crack via online APIs + hashcat/john"
tool "hashcat"             "(system) GPU hash cracking — hashcat -m MODE hash wordlist"
tool "john"                "(system) John the Ripper — CPU-based hash cracking"
tool "OneRuleToRuleThemAll" "~/Tools/OneRuleToRuleThemAll.rule — best hashcat mutation ruleset"
tool "cupp"                "~/Tools/cupp — build custom wordlists from target's personal info"
tool "flask-unsign"        "Brute-force Flask secret keys from captured session cookies"
tool "jwt_tool"            "~/Tools/jwt_tool — decode/forge/brute-force JWT tokens"
tool "kerberoast"          "AS-REP roast & Kerberoast — outputs hashcat/john compatible hashes"

# ─── STEGANOGRAPHY / FORENSICS ───────────────────────────────────────────────
header "STEGANOGRAPHY / FORENSICS"
tool "steghide"            "Hide/extract data in JPEG, BMP, WAV, AU files"
tool "pngcheck"            "Verify PNG integrity; dump chunk structure for CTF analysis"
tool "zbar-tools"          "zbarimg — scan & decode QR codes and barcodes from images"
tool "PcapXray"            "~/Tools/PcapXray — GUI network forensics tool for PCAP analysis"

# ─── SHELLS / REVERSE SHELLS ─────────────────────────────────────────────────
header "SHELLS / REVERSE SHELLS"
tool "pwncat-cs"           "Full-featured reverse/bind shell handler with module system"
tool "ConPtyShell"         "~/Tools/ConPtyShell — fully interactive Windows shell via ConPTY"
tool "RunasCs"             "~/Tools/RunasCs — run a process as another Windows user"
tool "powercat"            "~/Tools/powercat — PowerShell netcat with tunneling support"
tool "p0wny-shell"         "~/Tools/p0wny-shell — minimalist PHP web shell"
tool "php_reverse_shell"   "~/Tools/ivan_sineck_revshell.php — PHP reverse shell"
tool "PowerShell-RevShell" "~/Tools/PowerShell-Reverse-Shell-Generator — PS1 reverse shell"
tool "shell.sh"            "~/Tools/shell.sh — bash -c /dev/tcp one-liner wrapper"
tool "rustcat"             "Rust-based netcat replacement (listen: rc -l PORT)"
tool "rlwrap"              "Wrap any command with readline for arrow key/history support"

# ─── UTILITIES ───────────────────────────────────────────────────────────────
header "UTILITIES"
tool "anew"                "Append new unique lines from stdin to a file (tee+dedup)"
tool "gf"                  "Grep pattern templates for secrets, SQLi, SSRF, XSS, etc."
tool "fx"                  "Interactive terminal JSON viewer and processor"
tool "httpie"              "User-friendly HTTP client with syntax-highlighted output"
tool "html2text"           "Convert HTML pages to clean readable plain text"
tool "pywhat"              "Identify what a string is: hash type, IP range, encoding, etc."
tool "chardet"             "Detect character encoding of bytes/files"
tool "arsenal-cli"         "CLI cheatsheet assistant for offensive security commands"
tool "eza"                 "Modern ls: colors, icons, git status integration, tree view"
tool "fd-find"             "Fast, user-friendly find alternative (fd PATTERN [PATH])"
tool "bat"                 "cat with syntax highlighting and Git integration"
tool "fzf"                 "Fuzzy finder: files, shell history, processes, git, etc."
tool "jq"                  "Process, filter, and transform JSON from the command line"
tool "yq"                  "Process and transform YAML/JSON/XML from the command line"
tool "ripgrep (ag)"        "silversearcher-ag — blazing-fast recursive text search"
tool "ncdu"                "NCurses disk usage analyser — find what's consuming space"
tool "nnn"                 "Fast terminal file manager with plugin support"
tool "git-dumper"          "Dump exposed .git directories from web servers"
tool "git-vuln-finder"     "Find historical CVEs / vulnerabilities in git commit history"

printf "\n${YELLOW}Tip: pipe through 'less -R' for scrollable colour output, or filter with grep -i${RESET}\n\n"
