---
# main
install_code: false
install_sublime: true
xfce4_customizations: true

# install_vscode

# install_sublime
sublime_config_dir: "/home/{{ ansible_user }}/.config/sublime-text/Packages/User"

# xfce4_config
xfce_config_dir: "/home/{{ ansible_user }}/.config/xfce4"
display: ":0.0"

# install_fonts
font_temp_dir: "/tmp/fonts"
font_install_dir: "/home/{{ ansible_user }}/.local/share/fonts"
