---
- name: Update and Upgrade system
  hosts: all
  tags: pre-task
  become: true
  tasks:
    - name: Install apt-transport-https package
      ansible.builtin.apt:
        name: apt-transport-https
        state: present
        update_cache: true
        cache_valid_time: 3600

    # - name: Add Kali Linux GPG key
    #   ansible.builtin.apt_key:
    #     url: https://www.kali.org/archive-key.asc

    - name: Configure apt for HTTPS
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: "^deb http://"
        line: "deb https://mirrors.ocf.berkeley.edu/kali/ kali-rolling main contrib non-free"

    # This adds a repo, I want to change the main repo itself
    # - name: Configure Kali Linux repository
    #   ansible.builtin.apt_repository:
    #     repo: deb https://mirrors.ocf.berkeley.edu/kali/ kali-rolling main contrib non-free
    #     state: present
    #     filename: sources.list
    #     update_cache: true
    #     validate_certs: true

    - name: Run Apt update for new source and protocol
      tags: update
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Perform a full upgrade
      tags: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        autoclean: true
        autoremove: true
        # fail_on_autoremove: true

    # - name: Remove unwanted packages and dependencies
    #   ansible.builtin.apt:
    #     autoclean: true
    #     autoremove: true
