---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "stable"]
  push:
  workflow_dispatch:
  # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
