---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "stable"]
  push:
  workflow_dispatch:
  # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Install Ansible Colletion requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Debug - List installed collections
        run: ansible-galaxy collection list

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip
          pip install ansible ansible-lint

      - name: Run ansible-lint on the code base
        run: ansible-lint -v -s --project-dir .
